#ifndef COMMAND_HASHES_H
#define COMMAND_HASHES_H
// Autogenerated by HashWriter
// Confidential and Proprietary Qualcomm Technologies, Inc.
// NO PUBLIC DISCLOSURE PERMITTED:  Please report postings of this software on public servers or websites
// to: DocCtrlAgent@qualcomm.com.

// RESTRICTED USE AND DISCLOSURE:
// This software contains confidential and proprietary information and is not to be used, copied, reproduced, modified
// or distributed, in whole or in part, nor its contents revealed in any manner, without the express written permission
// of Qualcomm Technologies, Inc.
// Qualcomm is a trademark of QUALCOMM Incorporated, registered in the United States and other countries. All
// QUALCOMM Incorporated trademarks are used with permission
// This software may be subject to U.S. and international export, re-export, or transfer laws.  Diversion contrary to U.S.
// and international law is strictly prohibited.
// Qualcomm Technologies, Inc.
// 5775 Morehouse Drive
// San Diego, CA 92121 U.S.A.
// Copyright 2019-2024 Qualcomm Technologies, Inc.
// All rights reserved.
// Qualcomm Technologies Confidential and Proprietary

/*
	Author: Michael Simpson (msimpson@qti.qualcomm.com)
			Biswajit Roy (biswroy@qti.qualcomm.com)
*/

#include <QtGlobal>
#include "StringUtilities.h"

const HashType kVersionCommandHash(178099058);
const HashType kGetNameCommandHash(639527594);
const HashType kSetNameCommandHash(639527606);
const HashType kGetUUIDCommandHash(583302694);
const HashType kGetPlatformIDCommandHash(441876121);
const HashType kGetResetCountCommandHash(432158534);
const HashType kClearResetCountCommandHash(845787175);
const HashType kI2CReadRegisterCommandHash(333696227);
const HashType kI2CReadRegisterValueCommandHash(675332837);
const HashType kI2CWriteRegisterCommandHash(533512490);
const HashType kSetPinCommandHash(703510564);

// PIC32CX Hashes
const HashType kPIC32CXClearBufferHash(81534733);
const HashType kPIC32CXVersionCommandHash(22031998);
const HashType kPIC32CXSetPinCommandHash(15032008);

#endif // COMMAND_HASHES_H
