# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

# -- Version -----------------------------------------------------------
# version/release are overridden by generate-docs.py via confoverrides. These
# defaults only apply to a direct `sphinx-build` run in this directory.

version = "0.0.0"
release = version

# -- Project information -------------------------------------------------

project = "QTAC"
copyright = "Qualcomm Technologies, Inc. and/or its subsidiaries"
author = "Qualcomm Technologies, Inc."

# -- General configuration ------------------------------------------------

extensions = [
    "myst_parser",
    "pallets_sphinx_themes",
    "sphinx.ext.autosectionlabel",
    "sphinx_markdown_tables",
]

# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 3

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

master_doc = "index"

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Options for HTML output ----------------------------------------------

html_theme = "click"
html_static_path = ["resources"]
html_show_sourcelink = False
htmlhelp_basename = f"{project}-docs"
myst_heading_anchors = 3
